version: "3"
services:
  cli:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        # Dockerfileに環境変数を渡す
        - UID=${UID}
        - GID=${GID}
        - USERNAME=${USERNAME}
    volumes:
      - ~/.aws-gushi:/home/luna/.aws
      - ~/.ssh:/home/luna/.ssh
      - ./:/src
    working_dir: /src/iac/base
